name: flow

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Where to release?'
        required: true
        default: 'garage'
        options:
          - garage
          - yard
          - prod
      migrate:
        description: 'Run migration before deployment'
        type: boolean
        required: false
        default: false
      trpc_deploy:
        description: 'Build and deploy trpc'
        type: boolean
        required: false
        default: false
      webapp_deploy:
        description: 'Build and deploy webapp'
        type: boolean
        required: false
        default: false

# todo: add checkboxes for every cron job

jobs:
  # TODO: add check for release branches only
#  check_branch:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check branch name
#        run: |
#          branch_name=$(git branch --show-current)
#          if [[ $branch_name != release/R* ]]; then
#            echo "Error: Branch name must start with 'release/R'."
#            exit 1
#          fi

  echo_all:
    name: echo all
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "env ${{ github.event.inputs.environment }}"
          echo "migrate ${{ github.event.inputs.migrate }}"
          echo "trpc_deploy ${{ github.event.inputs.trpc_deploy }}"
          echo "webapp_deploy ${{ github.event.inputs.webapp_deploy }}"

  migrate:
    if: ${{ inputs.migrate == true }}
    name: Migrate database
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "migrate ${{ github.event.inputs.environment }} ${{ github.event.inputs.migrate }}"

  trpc_deploy:
    needs: migrate
    if: ${{ always() && inputs.trpc_deploy == true && (needs.migrate.result == 'success' || needs.migrate.result == 'skipped') }}
    name: Deploy TRPC
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "deploy trpc ${{ github.event.inputs.environment }} ${{ github.event.inputs.trpc_deploy }}"

  webapp_deploy:
    needs: trpc_deploy
    if: ${{ always() && inputs.webapp_deploy == true && (needs.trpc_deploy.result == 'success' || needs.trpc_deploy.result == 'skipped') }}
    name: Deploy webapp
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "deploy webapp ${{ github.event.inputs.environment }} ${{ github.event.inputs.webapp_deploy }}"

  echoing_list:
    runs-on: ubuntu-latest
    steps:
      - name: Create output variable
        id: get_true_vars
        run: |
          LIST=""
          if [ "${{ inputs.migrate }}" = true ]; then
            LIST="$LIST v migration\n"
          fi
          if [ "${{ inputs.webapp_deploy }}" = true ]; then
            LIST="$LIST v webapp\n"
          fi
          if [ "${{ inputs.trpc_deploy }}" = true ]; then
            LIST="$LIST v TRPC\n"
          fi
          echo "LIST=$LIST" >> $GITHUB_OUTPUT

      - name: Echo output variable
        run: |
          echo "True variables: ${{ steps.get_true_vars.outputs.LIST }}"
