name: flow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Where to release?'
        required: true
        default: 'garage'
        options:
          - garage
          - yard
          - prod
      migrate:
        description: 'Run migration before deployment'
        type: boolean
        required: false
        default: false
      trpc_deploy:
        description: 'Build and deploy trpc'
        type: boolean
        required: false
        default: false
      webapp_deploy:
        description: 'Build and deploy webapp'
        type: boolean
        required: false
        default: false

# todo: add checkboxes for every cron job

jobs:
  # TODO: add check for release branches only
  echo_all:
    name: echo all
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "env ${{ github.event.inputs.environment }}"
          echo "migrate ${{ github.event.inputs.migrate }}"
          echo "trpc_deploy ${{ github.event.inputs.trpc_deploy }}"
          echo "webapp_deploy ${{ github.event.inputs.webapp_deploy }}"

  migrate:
    if: ${{ inputs.migrate == true }}
    name: Migrate database
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "migrate ${{ github.event.inputs.environment }} ${{ github.event.inputs.migrate }}"

  trpc_deploy:
    needs: migrate
    if: ${{ always() && inputs.trpc_deploy == true && (needs.migrate.result == 'success' || needs.migrate.result == 'skipped') }}
    name: Deploy TRPC
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "deploy trpc ${{ github.event.inputs.environment }} ${{ github.event.inputs.trpc_deploy }}"

  webapp_deploy:
    needs: trpc_deploy
    if: ${{ inputs.webapp_deploy == true }}
    name: Deploy webapp
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "deploy webapp ${{ github.event.inputs.environment }} ${{ github.event.inputs.webapp_deploy }}"

