name: Create Github Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/R*'

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          branch_name="${{ github.ref_name }}" 
          if [[ $branch_name != release/R* ]]; then
              echo "Error: Branch name must start with 'release/R'."
            exit 1
          fi

  parse_version:
    needs: check_branch
    runs-on: ubuntu-latest
    name: Parse version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/release\///' | sed 's/R//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  echo_version:
    needs: parse_version
    runs-on: ubuntu-latest
    name: Echo version
    steps:
      - name: Echo
        run: echo ${{ needs.parse_version.outputs.version }}

  create_release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\///' | sed 's/R//')
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
          echo "RELEASE_NAME=Cool release $VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: true
          generate_release_notes: true
