name: Create Github Release

on:
  push:
    branches:
      - 'release/R*'

jobs:
  create_release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\///' | sed 's/R//')
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
          echo "RELEASE_NAME=Cool release $VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BRANCH=release/R$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Test
        run: echo ${{ github.ref }}

      - name: release-please-action
        uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: node

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          name: ${{ env.RELEASE_NAME }}
#          tag_name: ${{ env.TAG_NAME }}
#          target_commitish: ${{ github.sha }}
#          draft: false
#          prerelease: true
#          generate_release_notes: true
