name: Create Github Release

on:
  push:
    branches:
      - 'release/R*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\///' | sed 's/R//')
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
          echo "RELEASE_NAME=Release $VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            This is the release for version ${{ env.TAG_NAME }}.
          draft: false
          prerelease: false
