name: Create Github Release

on:
  push:
    branches:
      - 'release/R*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\///' | sed 's/R//')
          TAG_NAME=v$VERSION
          RELEASE_NAME="Release $VERSION"
          echo "::set-env name=TAG_NAME::$TAG_NAME"
          echo "::set-env name=RELEASE_NAME::$RELEASE_NAME"
          echo "::set-output name=VERSION::$VERSION"
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            This is the release for version ${{ env.TAG_NAME }}.
          draft: false
          prerelease: false
